language: python
python:
  - 3.7
install:
 - pip install -q -r requirements-dev.txt codecov
 - pip install -e .
script:
 - flake8
 - python -m pytest libpythonpro --cov=libpythonpro
after_success:
 - codecov