language: python
python:
  - 3.7
install:
 - pip install -e .
 - pip install --upgrade -q pipenv codecov
 - pipenv sync --dev
script:
 - flake8
 - pipenv check
 - bandit -r libpythonpro
 - python -m pytest --cov=libpythonpro
after_success:
 - codecov