language: python
python:
  - 3.7
install:
 - pip install -e .
 - pip install -q pipenv codecov
 - pipenv sync --dev
script:
 - flake8
 - python -m pytest libpythonpro --cov=libpythonpro
after_success:
 - codecov